package dao.impl;import dao.CrudDao;import model.CrudRecord;import util.DBUtil;import exception.AppException;import java.sql.*;import java.util.*;
public class GenericCrudDao<T extends CrudRecord> implements CrudDao<T>{private final String table,idCol; private final Class<T> type;
 public GenericCrudDao(String table,String idCol,Class<T> type){this.table=table;this.idCol=idCol;this.type=type;}
 public void insert(T r){String sql="INSERT INTO "+table+"(elder_id,col1,col2,col3,col4,note,record_time) VALUES(?,?,?,?,?,?,?)";try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement(sql)){fill(ps,r,false);ps.executeUpdate();}catch(Exception e){throw new AppException("新增資料失敗："+table,e);}}
 public List<T> findAll(){List<T> list=new ArrayList<>();try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("SELECT * FROM "+table+" ORDER BY "+idCol+" DESC");ResultSet rs=ps.executeQuery()){while(rs.next())list.add(map(rs));return list;}catch(Exception e){throw new AppException("查詢資料失敗："+table,e);}}
 public T findById(int id){try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("SELECT * FROM "+table+" WHERE "+idCol+"=?")){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){return rs.next()?map(rs):null;}}catch(Exception e){throw new AppException("依ID查詢失敗："+table,e);}}
 public void update(T r){String sql="UPDATE "+table+" SET elder_id=?,col1=?,col2=?,col3=?,col4=?,note=?,record_time=? WHERE "+idCol+"=?";try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement(sql)){fill(ps,r,true);ps.executeUpdate();}catch(Exception e){throw new AppException("修改資料失敗："+table,e);}}
 public void delete(int id){try(Connection c=DBUtil.getConnection();PreparedStatement ps=c.prepareStatement("DELETE FROM "+table+" WHERE "+idCol+"=?")){ps.setInt(1,id);ps.executeUpdate();}catch(Exception e){throw new AppException("刪除資料失敗："+table,e);}}
 private void fill(PreparedStatement ps,T r,boolean upd)throws SQLException{ps.setInt(1,r.getElderId());ps.setString(2,r.getCol1());ps.setString(3,r.getCol2());ps.setString(4,r.getCol3());ps.setString(5,r.getCol4());ps.setString(6,r.getNote());ps.setString(7,r.getRecordTime());if(upd)ps.setInt(8,r.getId());}
 private T map(ResultSet rs)throws Exception{T r=type.getDeclaredConstructor().newInstance();r.setId(rs.getInt(idCol));r.setElderId(rs.getInt("elder_id"));r.setCol1(rs.getString("col1"));r.setCol2(rs.getString("col2"));r.setCol3(rs.getString("col3"));r.setCol4(rs.getString("col4"));r.setNote(rs.getString("note"));r.setRecordTime(rs.getString("record_time"));return r;}
}
