CREATE DATABASE IF NOT EXISTS caremate_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE caremate_db;
DROP TABLE IF EXISTS translation_history, emergency_log, notification, contact, schedule, care_task, mood_record, meal_record, medicine_record, health_record, caregiver, elder, member;
CREATE TABLE member(member_id INT AUTO_INCREMENT PRIMARY KEY, account VARCHAR(50) UNIQUE NOT NULL, password VARCHAR(100) NOT NULL, name VARCHAR(50), role VARCHAR(30) NOT NULL, phone VARCHAR(30), email VARCHAR(100), status VARCHAR(20) DEFAULT 'ACTIVE', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE elder(elder_id INT AUTO_INCREMENT PRIMARY KEY, member_id INT, name VARCHAR(50), gender VARCHAR(20), birthday DATE, note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE caregiver(caregiver_id INT AUTO_INCREMENT PRIMARY KEY, member_id INT, name VARCHAR(50), nationality VARCHAR(50), language VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE health_record(health_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE medicine_record(medicine_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE meal_record(meal_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE mood_record(mood_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE care_task(task_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE schedule(schedule_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE contact(contact_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE notification(notification_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE emergency_log(emergency_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE translation_history(translation_id INT AUTO_INCREMENT PRIMARY KEY, elder_id INT DEFAULT 1, col1 VARCHAR(255), col2 VARCHAR(255), col3 VARCHAR(255), col4 VARCHAR(255), note TEXT, record_time VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO member(account,password,name,role,phone,email,status) VALUES('family','1234','家屬測試帳號','FAMILY','0912000000','family@test.com','ACTIVE'),('elder','1234','被照顧者測試帳號','ELDER','0912111111','elder@test.com','ACTIVE'),('caregiver','1234','外籍照顧者測試帳號','FOREIGN_CAREGIVER','0912222222','caregiver@test.com','ACTIVE'),('admin','1234','管理者','ADMIN','0912333333','admin@test.com','ACTIVE');
INSERT INTO elder(member_id,name,gender,birthday,note) VALUES(2,'阿公','男','1945-01-01','測試被照顧者');

-- Dashboard 2.0 demo data：首頁數據會依照以下資料與後續 CRUD 修改即時改變
INSERT INTO health_record(elder_id,col1,col2,col3,col4,note,record_time) VALUES(1,'125','82','36.6','上午','Dashboard 2.0 示範血壓體溫',DATE_FORMAT(NOW(),'%Y-%m-%dT%H:%i'));
INSERT INTO medicine_record(elder_id,col1,col2,col3,col4,note,record_time) VALUES(1,'血壓藥','1顆','早上','已完成','Demo 可於用藥頁修改狀態',DATE_FORMAT(NOW(),'%Y-%m-%dT%H:%i'));
INSERT INTO meal_record(elder_id,col1,col2,col3,col4,note,record_time) VALUES(1,'早餐','粥、蛋、青菜','350','已完成','Demo 可於飲食頁新增午餐晚餐',DATE_FORMAT(NOW(),'%Y-%m-%dT%H:%i'));
INSERT INTO mood_record(elder_id,col1,col2,col3,col4,note,record_time) VALUES(1,'開心','4','良好','照顧者回報','Demo 情緒資料',DATE_FORMAT(NOW(),'%Y-%m-%dT%H:%i'));
INSERT INTO care_task(elder_id,col1,col2,col3,col4,note,record_time) VALUES(1,'協助散步','照顧者','已完成','日常任務','Demo 今日任務',DATE_FORMAT(NOW(),'%Y-%m-%dT%H:%i'));
